# Generated by Django 3.1.7 on 2021-05-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeNewsDetector', '0002_userinfomodel_userloginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfomodel',
            name='Email',
        ),
    ]
